config/routes.rb
Joochify::Application.routes.draw do

  get 'word_lists/:tag', to: 'word_lists#show', as: :tag
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  match 'parola_search', to: 'home#parola_search', as: :parola_search, via: [:post]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :parolas
  resources :word_lists, only: [:index, :show]

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  layout 'home'
  
  def index
    @parola = Parola.new
  end
  
  
  def parola_search
    
    @parola = nil
    @parola = PgSearch.multisearch(params["parola"]["input"]).shuffle.map(&:searchable).first
    unless @parola
      @parola = Parola.create(input: params["parola"]["input"])
    end
        
    respond_to do |format|
      format.js
    end    
  end
  
  def about
  end
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_result.html.erb
<%= raw(@parola.formatted_result) %>

app/views/home/about.html.erb
<br />

<div class="form-wrapper">
	<div class="row">
		<div class="col-lg-10 col-lg-offset-1">
			<h1>About</h1>
			<p>&quot;Gabbagul Italian&quot; is the name that we've chosen to use for the "dialect" spoken by Italian-American 
				communities in the NY/NJ area. This "dialect" is predominantly influenced by Southern Italian dialects, reflecting the origins of the majority of the Italian immigrants in the area. Many of the words are derived from Italian (with some mutations) or are English words/phrases
				that show the influence of Italian speakers in their pronunciation.</p>
			<p><b>Joochify.it</b> contains a searchable dictionary that we've compiled of a number of these slang words. Searching will give 
				you the definition and root of the word. If we do not have the corresponding slang word, we attempt to create one for you.</p>
		</div>
	</div>
</div>
	
	<br />
	



<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		
		<%= image_tag "joochify_necklace.png"%>
		
	</div>
</div>

app/views/home/index.html.erb
<br />

<div class="form-wrapper">
	<div class="row">
		<div class="col-lg-10 col-lg-offset-1">
			<%= form_for @parola, url: parola_search_url, remote: true, html: { role: "form", class: "form-horizontal"} do |f| %>

						<h1>Joochify it. <small>Convert your vernacular to &quot;gabbagul Italian&quot;.</small></h1>

						<br />

						<div class="row">
							<div class="col-md-10">
									<%= f.text_field :input, placeholder: "Enter a word or phrase to joochify, e.g. calamari", class: "input-lg form-control" %>
							</div>
							<div class="col-md-2">
								<%= f.submit "Joochify it!", class: "btn btn-danger btn-lg", id: "joochify-button" %>
							</div>
						</div>


			<% end %>
		
		</div>
	</div>
	
	<br />
	
	<div class="row">
		<div class="col-lg-10 col-lg-offset-1" id="search-result">
			<div id="search_result_content" class="input-lg"><span class="placeholder">And you will get your result, e.g. galamad</span></div><br />
		</div>
	</div>
	<br />
	
	<div class="row">
		<div class="col-lg-5 col-lg-offset-1">
			<h5><%= link_to "About", about_url %></h5>
		</div>
		<div class="col-lg-4 col-lg-offset-1">
			<h5 class="pull-right"><%= link_to "Browse word lists by theme", word_lists_url %></h5>
		</div>
	</div>
	
</div>


<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		
		<%= image_tag "joochify_necklace.png"%>
		
	</div>
</div>

app/views/home/parola_search.js.erb
$("#search_result_content").html("<%= raw escape_javascript(render(:partial => 'result')) %>")