config/routes.rb
Joochify::Application.routes.draw do

  get 'word_lists/:tag', to: 'word_lists#show', as: :tag
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  match 'parola_search', to: 'home#parola_search', as: :parola_search, via: [:post]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :parolas
  resources :word_lists, only: [:index, :show]

  root 'home#index'

end

app/models/parola.rb
class Parola < ActiveRecord::Base
  include PgSearch
  
  acts_as_taggable
  before_create :convert
  validates_uniqueness_of :input
  default_scope { order('output') }
  multisearchable :against => [:input, :output, :definition]
  
 
  def has_definition?
    !self.definition.nil? and self.definition != ""
  end
  
  def has_part_of_speech?
    !self.part_of_speech.nil? and self.part_of_speech != ""
  end
  
  def has_etymology_language?
    !self.part_of_speech.nil? and self.part_of_speech != ""
  end
  
  def formatted_result
    
    result = self.output
    
    if self.has_part_of_speech?
      result += ", <b><i>#{self.part_of_speech}</i></b>"
    end
    
    if self.has_etymology_language?
      result += ", from the #{self.etymology_language} <i>#{self.input}</i>"
    end
    
    if self.has_definition?
      result += ", #{self.definition}"
    end
    
    result
    
  end
  
  def convert
    self.input = self.input.downcase
    self.output = self.input.downcase
    
    
    #### ENDINGS
    
    # get rid of that vowel ending first
    if !!(self.output[self.output.length-2] =~ /[aeiou]/ and self.output[self.output.length-1] =~ /[aeiou]/)
      self.output = self.output[0..self.output.length-3]
    elsif !!(self.output[self.output.length-1] =~ /[aeiou]/)
      self.output = self.output[0..self.output.length-2]
    end
        
    #drop the ending vowel of a word in a phrase if the next word starts with vowel
    split_array = self.output.split(" ")
    if split_array.size > 1
      split_array[0..split_array.length-2].each do |word|
        new_word = word
        if !!(split_array[split_array.index(word) + 1][0] =~ /[aeiou]/)
          if !!(word[word.length-2] =~ /[aeiou]/ and word[word.length-1] =~ /[aeiou]/)
            new_word = word[0..word.length-3]
          elsif !!(word[word.length-1] =~ /[aeiou]/)
            new_word = word[0..word.length-2]
          end
          
          #if a word originally ended in r-vowel or SINGLE t-vowel, make it hard (calamari -> calamad, scostumato -> scustumad)
          if split_array[split_array.index(word)][word.length-2] == "r" or 
            (split_array[split_array.index(word)][word.length-2] == "t" and split_array[split_array.index(word)][word.length-3] != "t")
            new_word[word.length-1] = "d"    
          # if a word ends in iolo, drop the o and make it iul (mariolo -> mariul')
          elsif !!(split_array[split_array.index(word)][word.length-2] =~ /[o]/) and 
            (split_array[split_array.index(word)][word.length-4..word.length-2] == "iol")
            new_word[word.length-2] = "u"
          elsif split_array[split_array.index(word)][word.length-3..word.length-2] == "ci" or 
            split_array[split_array.index(word)][word.length-3..word.length-2] == "ci"
            new_word[word.length-2..word.length-1] = "ch"
          elsif split_array[split_array.index(word)][word.length-3..word.length-2] == "zz"
            new_word[word.length-2..word.length-1] = "tz"
          elsif split_array[split_array.index(word)][word.length-3..word.length-2] == "gl"
            new_word[0..word.length-2] + "l"
          end
          
          
        end


        puts new_word
        split_array[split_array.index(word)] = new_word
      
      end
    end
    
    self.output = split_array.join("")
    
    #if a word originally ended in r-vowel or SINGLE t-vowel, make it hard (calamari -> calamad, scostumato -> scustumad)
    if self.input[self.input.length-2] == "r" or 
      (self.input[self.input.length-2] == "t" and self.input[self.input.length-3] != "t")
      self.output[self.output.length-1] = "d"
    elsif self.input[self.input.length-2] == "p"
      if self.input[self.input.length-3] != "p"
        self.output[self.output.length-1] = "b"
      else
        self.output = self.output[0..self.output.length-2]
      end
    # if a word ends in iolo, drop the o and make it iul (mariolo -> mariul')
    elsif !!(self.input[self.input.length-1] =~ /[o]/) and (self.input[self.input.length-4..self.input.length-2] == "iol")
      self.output[self.output.length-2] = "u"
    elsif self.input[self.input.length-3..self.input.length-1] == "sci"
      self.output[self.output.length-2..self.output.length-1] = "sh"
    elsif self.input[self.input.length-2..self.input.length-1] == "ci" or self.input[self.input.length-3..self.input.length-2] == "ci"
      self.output[self.output.length-2..self.output.length-1] = "ch"
    elsif self.output[self.output.length-2..self.output.length-1] == "zz"
      self.output[self.output.length-2..self.output.length-1] = "tz"
    elsif self.output[self.output.length-2..self.output.length-1] == "gl"
      self.output = self.output[0..self.output.length-3] + "l"
    elsif self.output[self.output.length-4..self.output.length-1] == "tell"
      self.output[self.output.length-4] = "d"
    elsif self.output[self.output.length-3..self.output.length-1] == "ucc"
      self.output[self.output.length-3..self.output.length-1] = "uke"
    end
    
    

    #### BEGINNINGS
    # if co appears at the beginning of a word, make it gu (coppino -> guppin')
    if !!(self.input[0..1] =~ /c[aou]/)
      self.output[0] = "g"
      if self.input[1] == "o"
        self.output[1] = "u"
      end
    elsif self.input[0..1] == "so" # if s*o appears at beginning of word, make it s*u (stonato -> stunad)
      self.output[1] = "u"
    elsif !!(self.input[0..2] =~ /[s][^f][o]/)
      self.output[2] = "u"
    elsif self.input[0..1] == "pu"
      self.output[0] = "b"
    elsif !!(self.input[0..2] =~ /[gc]iu/)
      self.output[0..2] = "joo"
    elsif self.input[0..1] == "ci"
      self.output[0] = "g"
    elsif self.input[0..3] == "mozz"
      self.output[0..1] = "mu"
    elsif self.input[0..2] == "qua"
      self.output[0] = "q"
    end
    
    
    ### MIDDLES
    self.output.gsub!("cil", "gil")
    self.output.gsub!("cci", "gi")   
    self.output.gsub!("scia", "sha")    
    self.output.gsub!(/([c][o])/, 'co' => 'go')
    
    
    # make it all one word
    self.output.gsub!(" ", "")
    
    if !!(self.output[self.output.length-1] =~ /[lmnt]/)
      self.output += "'"
    end
    
    return self.output
    
  end # end convert
  
end

app/controllers/parolas_controller.rb
class ParolasController < ApplicationController
  before_action :set_parola, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:new, :create]



  # GET /parolas
  # GET /parolas.json
  def index
    @parolas = Parola.all
  end

  # GET /parolas/1
  # GET /parolas/1.json
  def show
  end

  # GET /parolas/new
  def new
    @parola = Parola.new
  end

  # GET /parolas/1/edit
  def edit
  end

  # POST /parolas
  # POST /parolas.json
  def create
    @parola = Parola.new(parola_params)

    respond_to do |format|
      if @parola.save
        format.html { redirect_to @parola, notice: 'Parola was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parola }
      else
        format.html { render action: 'new' }
        format.json { render json: @parola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parolas/1
  # PATCH/PUT /parolas/1.json
  def update
    respond_to do |format|
      if @parola.update(parola_params)
        format.html { redirect_to parolas_url, notice: 'Parola was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parolas/1
  # DELETE /parolas/1.json
  def destroy
    @parola.destroy
    respond_to do |format|
      format.html { redirect_to parolas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parola
      @parola = Parola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parola_params
      params.require(:parola).permit(:input, :output, :definition, :part_of_speech, :etymology_language, :tag_list)
    end
end

app/helpers/parolas_helper.rb
module ParolasHelper
end

app/views/parolas/_form.html.erb
<%= form_for @parola, html: {role: "form", class: "form-horizontal"} do |f| %>
  <% if @parola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parola.errors.count, "error") %> prohibited this parola from being saved:</h2>

      <ul>
      <% @parola.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :input, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :input, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :output, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :output, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :part_of_speech, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.select :part_of_speech, ["n.", "v.", "adj.", "adv.", "phrase", "det.", "pro." ], {}, { class: "form-control" } %>
    </div>
    <%= f.label :etymology_language, "Etym. Language", class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.select :etymology_language, ["English", "Italian"], {}, { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "Tag List (comma-separated)", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :tag_list, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :definition, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :definition, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", {class: "btn btn-info"} %>
    </div>
  </div>

<% end %>

app/views/parolas/edit.html.erb
<h1>Editing parola</h1>

<%= render 'form' %>

app/views/parolas/index.html.erb
<h1>Listing parolas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Output</th>
      <th>Input</th>
			<th>Part of Speech</th>
			<th>Etymology Language</th>
			<th>Definition</th>
			<th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parolas.each do |parola| %>
      <tr>
        <td><%= parola.output %></td>
        <td><%= parola.input %></td>
				<td><%= parola.part_of_speech %></td>
				<td><%= parola.etymology_language %></td>
				<td><%= parola.definition %></td>
				<td><%= parola.tag_list %></td>
        <td><%= link_to 'Show', parola %></td>
        <td><%= link_to 'Edit', edit_parola_path(parola) %></td>
        <td><%= link_to 'Destroy', parola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parola', new_parola_path %>

app/views/parolas/new.html.erb
<h1>New parola</h1>

<%= render 'form' %>

<%= link_to 'Back', parolas_path %>

app/views/parolas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input:</strong>
  <%= @parola.input %>
</p>

<p>
  <strong>Output:</strong>
  <%= @parola.output %>
</p>

<%= link_to 'Edit', edit_parola_path(@parola) %> |
<%= link_to 'Back', parolas_path %>